variables:
  APP_NAME: "website"
  COMPONENT_NAME: "website-react"
  LIQUIBASE_CHANGELOG_DIR: "src/main/resources"
  DOCKER_CONTAINER_IMAGE: "docker.repo.devalex.consulting/finanztreff/website-react"
#  DOCKER_CONTAINER_TAG: $CI_COMMIT_SHORT_SHA
  NODE_OPTIONS: "--max_old_space_size=8192"
  BUILD_PATH: "dist/"
  DISABLE_ESLINT_PLUGIN: "true"

stages:
  - preparation
  - package
  - build
  - merge
  - test
  - stage
  - prod

include:
  - project: 'finanztreff/infra'
    ref: master
    file:
      - 'scripts/gitlab/.preparation-gitlab-ci.yml'
  - project: 'finanztreff/infra'
    ref: master
    file:
      - 'scripts/gitlab/.node-gitlab-ci.yml'
  - project: 'finanztreff/infra'
    ref: master
    file:
      - 'scripts/gitlab/.deployment-gitlab-ci.yml'
  - project: 'finanztreff/infra'
    ref: master
    file:
      - 'scripts/gitlab/.flow-gitlab-ci.yml'
